apiVersion: v1
kind: ConfigMap
metadata:
  name: skypay-config
data:
  # ===== General Spring =====
  SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
  SPRING_CLOUD_DISCOVERY_ENABLED: "false"
  SPRING_CONFIG_IMPORT: "optional:configserver:"  # disabled config server

  # ===== Service URLs =====
  API_GATEWAY_URL: "http://api-gateway:8080"
  USER_SERVICE_URL: "http://user-service:8081"
  ROOM_SERVICE_URL: "http://room-service:8082"
  BOOKING_SERVICE_URL: "http://booking-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service-mock:8084"

  # ===== Keycloak =====
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak:9090"
  KEYCLOAK_REALM: "hotel-realm"
  KEYCLOAK_RESOURCE: "hotel-client"
  KEYCLOAK_SSL_REQUIRED: "none"
  KEYCLOAK_PUBLIC_CLIENT: "true"

  # ===== Databases =====
  SPRING_DATA_MONGODB_URI: "mongodb://root:$(MONGO_PASSWORD)@mongo:27017/bookingdb?authSource=admin"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/hotel"
