apiVersion: v1
kind: Secret
metadata:
  name: skypay-secrets
type: Opaque
stringData:
  # MongoDB
  MONGO_USERNAME: "root"
  MONGO_PASSWORD: "rootpass"

  # Postgres
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"

  # Keycloak admin
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
