apiVersion: v1
kind: PersistentVolume
metadata:
  name: skypay-hotel-db-pv
  namespace: dev
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"