rootProject.name = 'SkyPay-hotel-system'
include 'api-common:api'
include 'modules:api-gateway'
include 'modules:user-service'
include 'modules:room-service'
include 'modules:booking-service'
include 'modules:payment-service-mock'
include 'infrastructures:eureka-server'
include 'infrastructures:spring-admin-server'
include 'infrastructures:config-server'
