spring:
  application:
    name: booking-service

  data:
    mongodb:
      host: mongo
      port: 27017
      database: bookingdb
      username: bookinguser
      password: bookingpass
      authentication-database: bookingdb

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/