apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: dev
spec:
  selector:
    app: skypay-hotel-tiers-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432